### ISSUE TITLE
TimeTable Backend change

### ISSUE THREAD

**Issue by Jenita** [Klartopedia/erp-api#559]

**Comment by sankar532564** [comment]
Hi @Jenita and @ArunprasadRajendran,

I can see new column(period_id) is added in TimeTable table. Due to this implementation Lecture page is not working). To fix that issue I have added period_id column in SubstitutionTeacher table(in dev DB). So please include this change also.
![image](https://github.com/Klartopedia/erp-api/assets/82047155/1007068b-3555-4b1c-8403-b6f76cee45aa)


For more information: https://github.com/Klartopedia/erp-api/issues/580
